Zamien funkcje mówienia czasu via *722 na wersje polska 
w pliku /etc/asterisk/extensions.conf

Wpisz do orginalnej funkcji znak ; na poczatku lini jak niżej:

; Say the time of day
;exten => TIME,1,ExecIfTime(0:00-11:59,*,*,*?Playback(rpt/goodmorning))
;	same => n,ExecIfTime(12:00-17:59,*,*,*?Playback(rpt/goodafternoon))
;	same => n,ExecIfTime(18:00-23:59,*,*,*?Playback(rpt/goodevening))
;	same => n,Playback(rpt/thetimeis)
;	same => n,SayUnixTime(RPT_TELEM_TIME(),,HM) ; Standard "say time"
;	;same => n,SayUnixTime(RPT_TELEM_TIME(),,${IF($[${STRFTIME(${UNIXTIME},,%-M) = 0}]?IMp:Ip)}) ; Alternate "say time" without o'clock
;	same => n,Hangup()


i wklej te wersje pond orginalna funkcja:

; Say the time of day Polska wersja
exten => TIME,1,ExecIfTime(0:00-11:59,*,*,*?Playback(rpt/goodmorning))
	same => n,ExecIfTime(12:00-17:59,*,*,*?Playback(rpt/goodafternoon))
	same => n,ExecIfTime(18:00-23:59,*,*,*?Playback(rpt/goodevening))
	same => n,Playback(rpt/thetimeis)
	same => n,Set(GODZINA=${STRFTIME(${EPOCH},,%H)})
	same => n,Set(MINUTY=${STRFTIME(${EPOCH},,%M)})
	same => n,Playback(digits/ho-${GODZINA})
	same => n,SayNumber(${MINUTY})
	same => n,Hangup()

