[ini]
# =========== Configuration ========================
# klucz API dla swojego konta z burze.dzis.net
key=123456789
#
# Współrzędne geograficzne punktu centralnego
# szerokość geograficzna
lat=53.02
# długość geograficzna
lon=18.36
#
# promień w km od punktu dla którego są pobierane alerty
range_detect=25

